//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel
{
    using System.Collections.Generic;
    
    
    public class PropertyExcelTextManager : Excel.IProperty
    {
        public Excel.PropertyExcelText[] propertyExcelText;
        
        public virtual Excel.PropertyExcelText[] PropertyExcelText
        {
            get
            {
                return this.propertyExcelText;
            }
            set
            {
                this.propertyExcelText = value;
            }
        }
        
        public override string TableName()
        {
            return "Sheet2";
        }
        
        public override void Split(Excel.Item[] objs)
        {
base.Split(objs);
PropertyExcelText = (Excel.PropertyExcelText[])objs;
        }
        
        public override string TableDir()
        {
            return "E://HePingWuGuan//策划//2_《和平武馆》配置表//常量表.xlsx";
        }
    }
}
