//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel
{
    
    
    [System.Serializable()]
    public class PropertyExcelText : Excel.Item
    {
        
        [UnityEngine.SerializeField()]
        private string constKey;
        
        [UnityEngine.SerializeField()]
        private string constValue;
        
        public virtual string ConstKey
        {
            get
            {
                return this.constKey;
            }
            set
            {
                this.constKey = value;
            }
        }
        
        public virtual string ConstValue
        {
            get
            {
                return  DataEncryptManager.StringDecoder(constValue);
            }
            set
            {
                this.constValue = value;
            }
        }
    }
}
